name: tripto
description: "TRIPTO 여행 애플리케이션 프로젝트."
publish_to: 'none'
version: 1.0.0+1

# SDK 버전 정의
environment:
  sdk: '>=3.0.0 <4.0.0'

# 외부 의존성 패키지 정의
dependencies:
  flutter:
    sdk: flutter
  
  # 다국어 지원 패키지
  flutter_localizations:
    sdk: flutter
    
  # 쿠퍼티노 아이콘 팩
  cupertino_icons: ^1.0.8
  
  # 프로필 이미지 선택기
  image_picker: ^1.1.2

  # 웹 뷰 패키지
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
  flutter_riverpod: ^3.3.2
  http: ^1.6.0

# 개발 전용 의존성 패키지 정의
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# 플러터 전역 자원 설정
flutter:
  uses-material-design: true

  # 로컬 이미지 에셋 등록
  assets:
    - assets/images/paperplane.png
    - assets/images/kakao_logo.png
    - assets/images/google_logo.png

  # 커스텀 서체 에셋 등록
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
